[package]
name = "nitro-primitives"
version = "0.1.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = { workspace = true }
bytes = "1"
alloy-rlp = { workspace = true }
alloy-primitives = { workspace = true }
arb-alloy-consensus = { workspace = true }
